"use client";

import { SegmentWithDetails } from "@/types/db";
import { useState } from "react";

interface SegmentsTableProps {
  segments: SegmentWithDetails[];
}

export function SegmentsTable({ segments }: SegmentsTableProps) {
  const [expandedId, setExpandedId] = useState<number | null>(null);

  return (
    <div className="bg-gray-800 rounded-lg border border-gray-700 overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead className="bg-gray-700">
            <tr>
              <th className="px-4 py-3 text-left text-sm font-semibold">Type</th>
              <th className="px-4 py-3 text-left text-sm font-semibold">Show</th>
              <th className="px-4 py-3 text-left text-sm font-semibold">AI Host</th>
              <th className="px-4 py-3 text-left text-sm font-semibold">Created</th>
              <th className="px-4 py-3 text-left text-sm font-semibold">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-700">
            {segments.map((segment) => (
              <>
                <tr
                  key={segment.id}
                  className="hover:bg-gray-700/50 transition-colors"
                >
                  <td className="px-4 py-3">
                    <span
                      className={`px-2 py-1 rounded text-xs font-medium ${
                        segment.type === "AI_TALK"
                          ? "bg-blue-500/20 text-blue-400"
                          : segment.type === "NEWS"
                            ? "bg-red-500/20 text-red-400"
                            : segment.type === "WEATHER"
                              ? "bg-cyan-500/20 text-cyan-400"
                              : "bg-yellow-500/20 text-yellow-400"
                      }`}
                    >
                      {segment.type}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-sm">
                    {segment.show?.name || "—"}
                  </td>
                  <td className="px-4 py-3 text-sm">
                    {segment.ai_host?.name || "—"}
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-400">
                    {new Date(segment.created_at).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-3">
                    <button
                      onClick={() =>
                        setExpandedId(expandedId === segment.id ? null : segment.id)
                      }
                      className="text-orange-500 hover:text-orange-400 text-sm"
                    >
                      {expandedId === segment.id ? "Hide" : "View"} Script
                    </button>
                  </td>
                </tr>
                {expandedId === segment.id && (
                  <tr>
                    <td colSpan={5} className="px-4 py-4 bg-gray-700/30">
                      <div className="space-y-2">
                        <div className="text-sm font-medium text-gray-300">
                          Script:
                        </div>
                        <div className="text-sm text-gray-400 bg-gray-800 p-3 rounded border border-gray-600 whitespace-pre-wrap">
                          {segment.text_script}
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
              </>
            ))}
          </tbody>
        </table>
        {segments.length === 0 && (
          <div className="p-8 text-center text-gray-400">
            No segments found. Segments are generated by the AI orchestrator.
          </div>
        )}
      </div>
    </div>
  );
}

